#if !canImport(ObjectiveC)
import XCTest

extension LZ4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LZ4Tests = [
        ("testCompressionDecompressionSmallInput", testCompressionDecompressionSmallInput),
    ]
}

extension StreamsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StreamsTests = [
        ("testCopyingString", testCopyingString),
        ("testWriteBufferToStringStream", testWriteBufferToStringStream),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LZ4Tests.__allTests__LZ4Tests),
        testCase(StreamsTests.__allTests__StreamsTests),
    ]
}
#endif
