#if !canImport(ObjectiveC)
import XCTest

extension LZ4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LZ4Tests = [
        ("testCompressionDecompressionSmallInput", testCompressionDecompressionSmallInput),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LZ4Tests.__allTests__LZ4Tests),
    ]
}
#endif
